# Generated by Django 5.2.2 on 2025-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=20),
        ),
    ]
